config/routes.rb
Rails.application.routes.draw do
  root to: "products#index"
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :price, presence: true, numericality: { greater_than: 0, less_than: 1_000_000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to root_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :code, :price, :img_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppWebManual</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= form_with model: @product do |f| %>
	<div>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</div>

	<div>
		<%= f.label :code %><br>
		<%= f.text_field :code %>
	</div>

	<div>
		<%= f.label :price %><br>
		<%= f.text_field :price %>
	</div>

	<div>
		<%= f.label :img_url %><br>
		<%= f.text_field :img_url %>
	</div>

	<div>
		<%= f.submit %>
	</div>
<% end %>

<%= link_to "Voltar", product_path %>
<%= link_to "Atualizar", products_path %>

app/views/products/index.html.erb
<h1>Products INDEX</h1>

<table border="1">
	<thead>
		<tr>
			<th>Nome</th>
			<th>Código</th>
			<th>Preço</th>
			<th>Link Imagem do Produto</th>
		</tr>
	</thead>
<tbody>
	<% @products.each do |product| %>
		<tr>
			<td><%= product.name %></td>
			<td><%= product.code %></td>
			<td><%= product.price %></td>
			<td><%= product.img_url %></td>
			<td>
				<%= link_to "Mostrar Produto", product %>
			</td>
		</tr>
	<% end %>
</tbody>
</table>
<br>
<%= link_to "Novo Produto", new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= form_with model: @product do |f| %>
	<div>
		<%= f.label :name %><br>
			<%= f.text_field :name %>
	</div>
	<div>
		<%= f.label :code %><br>
			<%= f.text_field :code %>
	</div>
	<div>
		<%= f.label :price %><br>
			<%= f.number_field  :price,  min: 0, step: 0.1 %>
	</div>
	<div>
		<%= f.label :img_url %><br>
			<%= f.text_field :img_url %>
	</div>
	<div>
		<%= f.submit %>
	</div>
	<% end %>

	<p>
		<%= link_to "Voltar", products_path %>
	</p>

app/views/products/show.html.erb
<h1>Exibir Produtos</h1>

<p>
	<strong>Nome:</strong>
	<%= @product.name %>
</p>

<p>
	<strong>Código:</strong>
	<%= @product.code %>
</p>

<p>
	<strong>Preço:</strong>
	<%= @product.price %>
</p>

<p>
	<strong>URL:</strong>
	<%= @product.img_url %>
</p>

<%= link_to "Voltar", products_path %>
<%= link_to "Editar", edit_product_path(@product)%>
<%= link_to "Deletar", product_path, method: :delete, data: { confirm: "Tem certeza?" } %>